blank_issues_enabled: false
contact_links:
  - name: Daktilograf STT GitHub Discussions
    url: https://github.com/OM3GA-SOLUTIONS-d-o-o/daktilograf-V3-client/discussions
    about: Please ask and answer questions here.
  - name: Daktilograf Security issue disclosure
    url: mailto:kontakt@om3ga.org
    about: Please report security vulnerabilities here.
